# Generated by Django 3.2.8 on 2021-11-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
    ]
