# Generated by Django 3.2.8 on 2021-11-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_reviews_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название языка')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('duration', models.CharField(max_length=10, verbose_name='Количество затраченного времени')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('about', models.CharField(max_length=150, verbose_name='О проекте')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.language', verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Моя работа',
                'verbose_name_plural': 'Мои работы',
            },
        ),
    ]
