# Generated by Django 3.2.8 on 2021-11-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_works_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='url',
            field=models.CharField(max_length=160, verbose_name='Url'),
        ),
    ]
