# Generated by Django 3.2.8 on 2021-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_works_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=150, verbose_name='Отзыв')),
                ('work', models.CharField(max_length=50, verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Отзыв о работе',
                'verbose_name_plural': 'Отзывы о работе',
            },
        ),
    ]
